name = "RegularizedProblems"
uuid = "ea076b23-609f-44d2-bb12-a4ae45328278"
authors = [
  "Dominique Orban <dominique.orban@gmail.com>, Robert Baraldi <robertjbaraldi@gmail.com",
]
version = "0.1.2"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ManualNLPModels = "30dfa513-9b2f-4fb3-9796-781eabac1617"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
Noise = "81d43f40-5267-43b7-ae1c-8b967f377efa"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ShiftedProximalOperators = "d4fd37fa-580c-4e43-9b30-361c21aae263"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
QuadraticModels = "f468eda6-eac5-11e8-05a5-ff9e497bcd19"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"

[extensions]
FHExt = ["ADNLPModels", "DifferentialEquations", "SciMLSensitivity"]
QPRandExt = "QuadraticModels"
SVMExt = "MLDatasets"

[compat]
ADNLPModels = "0.7, 0.8"
DifferentialEquations = "7.16"
Distributions = "0.25"
LinearAlgebra = "1.10, 1.11"
ManualNLPModels = "0.2"
MLDatasets = "0.7"
NLPModels = "0.16, 0.17, 0.18, 0.19, 0.20, 0.21"
Noise = "0.2"
ProximalOperators = "0.15, 0.16"
Random = "1.10, 1.11"
QuadraticModels = "0.9"
SciMLSensitivity = "7.89"
ShiftedProximalOperators = "0.2"
SparseArrays = "1.10, 1.11"
julia = "1.10"
